version: 0.0
os: linux
files:
  - source: target/weather_api-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/weather_api
hooks:
  BeforeInstall:
    - location: scripts/clean.sh
      timeout: 3000
      runas: root
  ApplicationStart:
    - location: scripts/startup.sh
      timeout: 30000
      runas: root
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 3000
      runas: root
#  ValidateService:
#    - location: scripts/validate.sh
#      timeout: 3000
#      runas: root