version: 0.0
os: linux
files:
  - source: ./target/weather_api-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/weather_api/weather_api-0.0.1-SNAPSHOT.jar
hooks:
  BeforeInstall:
    - location: scripts/clean.sh
      timeout: 30000
      runas: root
  AfterInstall:
    - location: scripts/startup.sh
      timeout: 30000
      runas: root
